Feature/INT-1248_radio_button
avarteqgmbh/design-system pull request #15
Opened 2021-07-12 11:33 UTC by kristelaK

2021-07-12 15:34 UTC, r3p0x requested changes
Looks really good, but you forgot the exports in the index, did you?

2021-07-12 15:34 UTC, r3p0x commented on src/components/inputs/ButtonGroup/ButtonGroup.stories.tsx
> +        type: { summary: 'boolean' },
thank you for that one 👍

2021-07-14 06:31 UTC, kristelaK commented
> Looks really good, but you forgot the exports in the index, did you?

I am not done with the ticket yet. When I am done I comment the PR to the ticket and flag it so the other person can pull it to internal review for CR. :)

2021-07-19 07:13 UTC, Momen-a9s requested changes

2021-07-19 07:13 UTC, Momen-a9s commented on src/components/inputs/Radio/Radio.tsx
> +export function Radio(props: RadioProps) {
maybe remove the ESlint disable line
```
export function Radio(props: RadioProps): JSX.Element {
```

2021-07-19 07:13 UTC, Momen-a9s commented on src/components/inputs/Radio/Radio.stories.tsx
> +  return <Radio {...args}> Radio </Radio>
maybe `<Radio {...args} />`

2021-07-19 07:13 UTC, Momen-a9s commented on src/components/inputs/Radio/Radio.stories.tsx
> +    },
for `checked` and `disabled` if you make values = 'true' and 'false' it will equal true every time and it isn't work in the storybook view
```
    checked: {
      control: { type: 'boolean' },
      defaultValue: false,
      table: {
        type: { summary: 'boolean' },
        defaultValue: { summary: false }
      }
    },
    disabled: {
      control: { type: 'boolean' },
      defaultValue: false,
      table: {
        type: { summary: 'boolean' },
        defaultValue: { summary: false }
      }
    },
```

2021-07-19 07:13 UTC, Momen-a9s commented on src/components/inputs/Radio/Radio.stories.tsx
> +  size: 'medium'
to preview the color you need to add also
`checked: true,`
it appeared because the options for the `checked` attribute is wrong

2021-07-19 07:23 UTC, Momen-a9s commented on package.json
> +    "sb": "node -e 'require(\"./fix-eslint\").removeTsConfig()' &&start-storybook -p 6006 -s public",
Thanks for adding 🙏

2021-07-19 07:26 UTC, Momen-a9s commented on package.json
> +    "storybook-addon-designs": "^6.0.0",
I am curious, why we need to add this Lib, Thanks 🙏

2021-07-19 08:15 UTC, kristelaK commented on package.json
> +    "storybook-addon-designs": "^6.0.0",
@Momen-a9s I just moved it from dependencies to dev dep because eslint showed an error that it should be there.

2021-07-19 08:20 UTC, kristelaK commented
@Momen-a9s Could you please take a look at the changes?

2021-07-19 08:24 UTC, Momen-a9s approved these changes
Great work, Thanks for changes

2021-07-19 08:24 UTC, Momen-a9s commented on src/components/inputs/Radio/Radio.stories.tsx
> +}
for `Default` you can remove all these attributes to be like a clean element

2021-07-19 08:34 UTC, kristelaK commented on src/components/inputs/Radio/Radio.stories.tsx
> +}
@Momen-a9s Color and size have the default value and checked I added just to see the color.

2021-07-19 08:36 UTC, merged