Feature/int 1261 tabs components
avarteqgmbh/design-system pull request #36
Opened 2021-07-25 18:50 UTC by sabbir0179

2021-07-26 07:00 UTC, Momen-a9s requested changes
The branch didn't work locally with me, please check the comment in tab stories

2021-07-30 12:10 UTC, sabbir0179 commented on src/components/navigation/Tabs/TabPanel.tsx
> +    <div
This is a custom TabPanel component designed for the Tabs, as shown in Tabs example. Certain props that were used here weren't supported in Mui_tab_panel component given by default.

2021-07-30 12:21 UTC, sabbir0179 commented on src/components/navigation/Tabs/Tabs.stories.tsx
> +
fixed

2021-07-30 12:21 UTC, sabbir0179 commented on src/components/navigation/Tabs/Tabs.stories.tsx
> +    event: React.ChangeEvent<{}>,
fixed it

2021-07-30 12:47 UTC, Momen-a9s approved these changes
nice work, thanks for changes

2021-07-30 13:30 UTC, merged